name: flutter_application_1
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  # Firebase dependencies
  firebase_core: ^4.2.0
  firebase_auth: ^6.1.1
  cloud_firestore: ^6.0.3
  cloud_functions: ^6.0.3

  # Authentication
  google_sign_in: ^6.2.1

  # Device information
  device_info_plus: ^10.1.0

  # Network requests
  http: ^1.2.2

  # Email sending
  mailer: ^6.2.0

  # Utilities
  uuid: ^4.5.1
  shared_preferences: ^2.3.3

  # UI & Fonts
  google_fonts: ^6.1.0
  flutter_svg: ^2.1.1
  cupertino_icons: ^1.0.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true